#!/bin/bash

#==============================================================================
# Absolute path to this script, e.g. /Users/rudolf/mobileweb_camcops/SHIP_DOCS.sh
#==============================================================================

LOCALBASEDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
KEYSTOREFILE=~/CAMCOPS_ANDROID_KEYSTORE.bin

#==============================================================================
# Build
#==============================================================================

# *** need to get the "distribute" option working

# Build for device/emulator:
# titanium build --platform android --project-dir $LOCALBASEDIR --target device

# Build for distribution
if [[ "$KEYSTORE_PASSWORD" == "" ]]; then
    echo "No KEYSTORE_PASSWORD environment variable set"
    echo -n "Keystore password: "
    read KEYSTORE_PASSWORD
    echo
fi
titanium build \
    --platform android \
    --project-dir $LOCALBASEDIR \
    --target dist-playstore \
    --keystore $KEYSTOREFILE \
    --store-password $KEYSTORE_PASSWORD \
    --alias camcops \
    --output-dir $LOCALBASEDIR/dist \
    || exit 1

# To make a keypair, before this will work:
# keytool -genkeypair -v -alias camcops -keyalg RSA -keysize 2048 -validity 36500 -keystore ../camcops_android_keystore -dname "CN=Rudolf Cardinal, OU=Department of Psychiatry, O=University of Cambridge, L=Cambridge, ST=Cambridgeshire, C=UK"

# The keystore lives outside the CamCOPS repository (for security).

# Extract version number from tiapp.xml
CAMCOPS_VERSION=`perl -ne 'print $1 if /<version>([\d\.]*)<\/version>/;' $LOCALBASEDIR/tiapp.xml`

SRCAPK=$LOCALBASEDIR/dist/CamCOPS.apk
DSTAPK=$LOCALBASEDIR/dist/camcops_${CAMCOPS_VERSION}.apk
mv $SRCAPK $DSTAPK || exit 1

echo "Made $DSTAPK"

# IF THIS SCRIPT FAILS, run "titanium info" and check for problems.
# ... and "titanium config" -- which by default reads ~/.titanium/config.json
