#!/bin/sh

# from Illustrator: Save for Web > Image Size > width 1344, height 3264 > Apply > Save > sliceme.png
# ... based on each square being 96x96

mkdir output
cd output

# chop: amount to remove at LEFT x TOP
convert ../sliceme.png -crop 96x96 +repage tile-%d.png

#mv tile-0.png TEST_BLUE.png
#mv tile-1.png TEST_RED.png
#mv tile-15.png TEST_EMPTY.png

mv tile-30.png finishflag.png
mv tile-32.png finishflag_T.png
mv tile-34.png camcops.png
mv tile-36.png executive.png
mv tile-38.png locked.png
mv tile-40.png locked_T.png

mv tile-58.png speaker.png
mv tile-60.png speaker_T.png
mv tile-62.png choose_patient.png
mv tile-64.png research.png
mv tile-66.png unlocked.png
mv tile-68.png unlocked_T.png

mv tile-86.png speaker_playing.png
mv tile-88.png speaker_playing_T.png
mv tile-90.png upload.png
mv tile-92.png info.png
mv tile-94.png back.png
mv tile-96.png back_T.png

# mv tile-114.png reload.png # OLD RELOAD
# mv tile-116.png reload_T.png # OLD RELOAD
mv tile-118.png settings.png
# info2
mv tile-122.png next.png
mv tile-124.png next_T.png

mv tile-142.png camera.png
mv tile-144.png camera_T.png
mv tile-146.png global.png
mv tile-148.png patient_summary.png
mv tile-150.png add.png
mv tile-152.png add_T.png

mv tile-170.png radio_selected.png
mv tile-172.png radio_selected_T.png
mv tile-174.png cognitive.png
convert tile-176.png -resize 24x24 hasChild.png
convert hasChild.png -flop hasParent.png
mv tile-178.png cancel.png
mv tile-180.png cancel_T.png

mv tile-198.png radio_unselected.png
mv tile-200.png radio_unselected_T.png
mv tile-202.png affective.png
mv tile-204.png clinical.png
mv tile-206.png edit.png
mv tile-208.png edit_T.png

mv tile-226.png check_true_red.png
mv tile-228.png check_true_red_T.png
mv tile-230.png addiction.png
mv tile-232.png anonymous.png
mv tile-234.png delete.png
mv tile-236.png delete_T.png

mv tile-254.png check_unselected.png
mv tile-256.png check_unselected_T.png
mv tile-258.png psychosis.png
mv tile-260.png check_unselected_required.png
mv tile-262.png ok.png
mv tile-264.png ok_T.png

mv tile-282.png check_true_black.png
mv tile-284.png check_true_black_T.png
mv tile-286.png catatonia.png
mv tile-288.png radio_unselected_required.png
mv tile-290.png finish.png
mv tile-292.png finish_T.png

mv tile-310.png check_false_black.png
mv tile-312.png check_false_black_T.png
mv tile-314.png personality.png
mv tile-316.png stop.png
mv tile-318.png zoom.png
mv tile-320.png zoom_T.png

mv tile-338.png check_false_red.png
mv tile-340.png check_false_red_T.png
mv tile-342.png field_incomplete_mandatory.png
mv tile-344.png field_problem.png
mv tile-346.png privileged.png
mv tile-348.png privileged_T.png

mv tile-366.png sets_research.png
mv tile-368.png sets_clinical.png
mv tile-370.png alltasks.png
mv tile-372.png warning.png
mv tile-374.png time_now.png
mv tile-376.png time_now_T.png

mv tile-394.png reload.png
mv tile-396.png reload_T.png
mv tile-398.png rotate_clockwise.png
mv tile-400.png rotate_clockwise_T.png
mv tile-402.png rotate_anticlockwise.png
mv tile-404.png rotate_anticlockwise_T.png

mv tile-422.png choose_page.png
mv tile-424.png choose_page_T.png
mv tile-426.png read_only.png
mv tile-428.png field_incomplete_optional.png
mv tile-430.png chain.png
mv tile-432.png whisker.png

mv tile-450.png fast_forward.png
mv tile-452.png fast_forward_T.png
mv tile-454.png check_disabled.png
mv tile-456.png radio_disabled.png

rm tile*.png
