# .readthedocs.yaml

# See
# - https://docs.readthedocs.io/en/stable/config-file/index.html
# - https://docs.readthedocs.io/en/latest/yaml-config.html
# - https://docs.readthedocs.io/en/latest/config-file/v2.html
# - https://github.com/rtfd/readthedocs.org/issues/2139

version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - method: pip
      path: server
