// COLOURS.js

/*
    Copyright (C) 2012-2015 Rudolf Cardinal (rudolf@pobox.com).
    Department of Psychiatry, University of Cambridge.
    Funded by the Wellcome Trust.

    This file is part of CamCOPS.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

/*jslint node: true */

module.exports = {
    BLACK               : '#000000',
    NAVY                : '#000080',
    DARKBLUE            : '#00008B',
    MEDIUMBLUE          : '#0000CD',
    BLUE                : '#0000FF',
    DARKGREEN           : '#006400',
    GREEN               : '#008000',
    TEAL                : '#008080',
    DARKCYAN            : '#008B8B',
    DEEPSKYBLUE         : '#00BFFF',
    DARKTURQUOISE       : '#00CED1',
    MEDIUMSPRINGGREEN   : '#00FA9A',
    LIME                : '#00FF00',
    SPRINGGREEN         : '#00FF7F',
    AQUA                : '#00FFFF',
    CYAN                : '#00FFFF',
    MIDNIGHTBLUE        : '#191970',
    DODGERBLUE          : '#1E90FF',
    LIGHTSEAGREEN       : '#20B2AA',
    FORESTGREEN         : '#228B22',
    SEAGREEN            : '#2E8B57',
    DARKSLATEGRAY       : '#2F4F4F',
    LIMEGREEN           : '#32CD32',
    MEDIUMSEAGREEN      : '#3CB371',
    TURQUOISE           : '#40E0D0',
    ROYALBLUE           : '#4169E1',
    STEELBLUE           : '#4682B4',
    DARKSLATEBLUE       : '#483D8B',
    MEDIUMTURQUOISE     : '#48D1CC',
    INDIGO              : '#4B0082',
    DARKOLIVEGREEN      : '#556B2F',
    CADETBLUE           : '#5F9EA0',
    CORNFLOWERBLUE      : '#6495ED',
    MEDIUMAQUAMARINE    : '#66CDAA',
    DIMGRAY             : '#696969',
    SLATEBLUE           : '#6A5ACD',
    OLIVEDRAB           : '#6B8E23',
    SLATEGRAY           : '#708090',
    LIGHTSLATEGRAY      : '#778899',
    MEDIUMSLATEBLUE     : '#7B68EE',
    LAWNGREEN           : '#7CFC00',
    CHARTREUSE          : '#7FFF00',
    AQUAMARINE          : '#7FFFD4',
    MAROON              : '#800000',
    PURPLE              : '#800080',
    OLIVE               : '#808000',
    GRAY                : '#808080',
    SKYBLUE             : '#87CEEB',
    LIGHTSKYBLUE        : '#87CEFA',
    BLUEVIOLET          : '#8A2BE2',
    DARKRED             : '#8B0000',
    DARKMAGENTA         : '#8B008B',
    SADDLEBROWN         : '#8B4513',
    DARKSEAGREEN        : '#8FBC8B',
    LIGHTGREEN          : '#90EE90',
    MEDIUMPURPLE        : '#9370DB',
    DARKVIOLET          : '#9400D3',
    PALEGREEN           : '#98FB98',
    DARKORCHID          : '#9932CC',
    YELLOWGREEN         : '#9ACD32',
    SIENNA              : '#A0522D',
    BROWN               : '#A52A2A',
    DARKGRAY            : '#A9A9A9',
    PROPERLYDARKGRAY    : '#404040', // RNC
    VERYLIGHTGREEN      : '#C8FFC8', // RNC
    LIGHTBLUE           : '#ADD8E6',
    GREENYELLOW         : '#ADFF2F',
    PALETURQUOISE       : '#AFEEEE',
    LIGHTSTEELBLUE      : '#B0C4DE',
    POWDERBLUE          : '#B0E0E6',
    FIREBRICK           : '#B22222',
    DARKGOLDENROD       : '#B8860B',
    MEDIUMORCHID        : '#BA55D3',
    ROSYBROWN           : '#BC8F8F',
    DARKKHAKI           : '#BDB76B',
    SILVER              : '#C0C0C0',
    MEDIUMVIOLETRED     : '#C71585',
    INDIANRED           : '#CD5C5C',
    PERU                : '#CD853F',
    CHOCOLATE           : '#D2691E',
    TAN                 : '#D2B48C',
    LIGHTGRAY           : '#D3D3D3',
    THISTLE             : '#D8BFD8',
    ORCHID              : '#DA70D6',
    GOLDENROD           : '#DAA520',
    PALEVIOLETRED       : '#DB7093',
    CRIMSON             : '#DC143C',
    GAINSBORO           : '#DCDCDC',
    PLUM                : '#DDA0DD',
    BURLYWOOD           : '#DEB887',
    LIGHTCYAN           : '#E0FFFF',
    LAVENDER            : '#E6E6FA',
    DARKSALMON          : '#E9967A',
    VIOLET              : '#EE82EE',
    PALEGOLDENROD       : '#EEE8AA',
    LIGHTCORAL          : '#F08080',
    KHAKI               : '#F0E68C',
    ALICEBLUE           : '#F0F8FF',
    HONEYDEW            : '#F0FFF0',
    AZURE               : '#F0FFFF',
    SANDYBROWN          : '#F4A460',
    WHEAT               : '#F5DEB3',
    BEIGE               : '#F5F5DC',
    WHITESMOKE          : '#F5F5F5',
    MINTCREAM           : '#F5FFFA',
    GHOSTWHITE          : '#F8F8FF',
    SALMON              : '#FA8072',
    ANTIQUEWHITE        : '#FAEBD7',
    LINEN               : '#FAF0E6',
    LIGHTGOLDENRODYELLOW : '#FAFAD2',
    OLDLACE             : '#FDF5E6',
    RED                 : '#FF0000',
    FUCHSIA             : '#FF00FF',
    MAGENTA             : '#FF00FF',
    DEEPPINK            : '#FF1493',
    ORANGERED           : '#FF4500',
    TOMATO              : '#FF6347',
    HOTPINK             : '#FF69B4',
    CORAL               : '#FF7F50',
    DARKORANGE          : '#FF8C00',
    LIGHTSALMON         : '#FFA07A',
    ORANGE              : '#FFA500',
    LIGHTPINK           : '#FFB6C1',
    PINK                : '#FFC0CB',
    GOLD                : '#FFD700',
    PEACHPUFF           : '#FFDAB9',
    NAVAJOWHITE         : '#FFDEAD',
    MOCCASIN            : '#FFE4B5',
    BISQUE              : '#FFE4C4',
    MISTYROSE           : '#FFE4E1',
    BLANCHEDALMOND      : '#FFEBCD',
    PAPAYAWHIP          : '#FFEFD5',
    LAVENDERBLUSH       : '#FFF0F5',
    SEASHELL            : '#FFF5EE',
    CORNSILK            : '#FFF8DC',
    LEMONCHIFFON        : '#FFFACD',
    FLORALWHITE         : '#FFFAF0',
    SNOW                : '#FFFAFA',
    YELLOW              : '#FFFF00',
    LIGHTYELLOW         : '#FFFFE0',
    IVORY               : '#FFFFF0',
    WHITE               : '#FFFFFF',

    // RNC extras
    VIVIDCYAN           : '#0088FF',
    BLUEGREEN           : '#336699',
    GRAY10              : '#191919',
    GRAY20              : '#333333',
    GRAY75              : '#BFBFBF',
    GRAY80              : '#CCCCCC',
    GRAY90              : '#E6E6E6',
    AMBER               : '#FF7E00',
    PALEYELLOW          : '#FFFFD0',
    PALEBLUE            : '#DDDDFF',
};
