#!/bin/bash

#==============================================================================
# Absolute path to this script, e.g. /Users/rudolf/mobileweb_camcops/SHIP_DOCS.sh
#==============================================================================

LOCALBASEDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

#==============================================================================
# Build and launch to iOS simulator
#==============================================================================

node /usr/local/bin/titanium \
    build \
    --platform ipad \
    --log-level trace \
    --sdk 3.5.1.GA \
    --project-dir $LOCALBASEDIR \
    --target simulator \
    --ios-version 8.3 \
    --device-family ipad \
    --deploy-type development \
    --sim-type ipad \
    --sim-version 8.3 \
    --device-id 1EE9E9CC-4562-4D15-B9AF-88C0D73A8988 \
    --skip-js-minify

# If it works from the Studio but not here, use "ps aux | grep titanium" to
# capture what the Studio's doing.
