#!/bin/bash

#==============================================================================
# Absolute path to this script, e.g. /Users/rudolf/mobileweb_camcops/SHIP_DOCS.sh
#==============================================================================

LOCALBASEDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

#==============================================================================
# Make for MobileWeb
#==============================================================================

# *** need to get the "distribute" option working

titanium build \
    --platform mobileweb \
    --project-dir $LOCALBASEDIR
