#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

if [ "$0" != "bash" ] && [ "$0" != "-bash" ]; then
    echo "Execute this as 'source $0' or '. $0' or it will do nothing"
    exit 1
fi

export CAMCOPS_IOS_DEVICE_ID=610D050B-29FE-4F1F-A025-EEA4E6206DC9
export CAMCOPS_IOS_VERSION=8.4
# export CAMCOPS_TITANIUM_SDK_VERSION=3.5.1.GA
export CAMCOPS_TITANIUM_SDK_VERSION=5.1.2.GA
