#!/bin/bash

#==============================================================================
# Absolute path to this script, e.g. /Users/rudolf/mobileweb_camcops/SHIP_DOCS.sh
#==============================================================================

LOCALBASEDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

#==============================================================================
# Ship
#==============================================================================

# Extract version number from tiapp.xml
CAMCOPS_VERSION=`perl -ne 'print $1 if /<version>([\d\.]*)<\/version>/;' $LOCALBASEDIR/tiapp.xml`

# for the proper build:
LOCALAPKPATH=$LOCALBASEDIR/dist
APK=camcops_${CAMCOPS_VERSION}.apk

REMOTEUSER="rudolf"
REMOTEHOST="egret"
CONN=$REMOTEUSER@$REMOTEHOST
REMOTEANDROIDDIR="/srv/www/camcops/download/android"

echo "Distributing $LOCALAPKPATH/$APK to $CONN:$REMOTEANDROIDDIR/$APK"

scp $LOCALAPKPATH/$APK $CONN:$REMOTEANDROIDDIR/$APK
