#!/bin/bash

# Minimal simple script to dump all current MySQL databases.
# This file must be READABLE ONLY BY ROOT (or equivalent, backup)!
# The password is in cleartext.
# Once you have copied this file and edited it, perform:
#     sudo chown root:root &lt;filename&gt;
#     sudo chmod 700 &lt;filename&gt;
# Then you can add it to your /etc/crontab for regular execution.

BACKUPDIR=&#x27;/var/backups/mysql&#x27;
BACKUPFILE=&#x27;all_my_mysql_databases.sql&#x27;
USERNAME=&#x27;root&#x27;  # MySQL username
PASSWORD=&#x27;PPPPPP_REPLACE_ME&#x27;  # MySQL password

# Make directory unless it exists already:
mkdir -p $BACKUPDIR

# Dump the database:
mysqldump -u $USERNAME -p$PASSWORD --all-databases --force &gt; $BACKUPDIR/$BACKUPFILE

# Make sure the backups (which may contain sensitive information) are only
# readable by the &#x27;backup&#x27; user group:
cd $BACKUPDIR
chown -R backup:backup *
chmod -R o-rwx *
chmod -R ug+rw *

