#!/usr/bin/env bash
# server/docker/linux/upgrade_db
#
# Launches the "camcops_server upgrade_db" command within a new Docker
# container running the CamCOPS server image.

set -e

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
CAMCOPS_SERVER="${THIS_DIR}/camcops_server"

if [ -z "${CAMCOPS_DOCKER_CONFIG_HOST_DIR}" ]; then
    echo "Must set CAMCOPS_DOCKER_CONFIG_HOST_DIR environment variable!"
    exit 1
    # Note that Linux is permissive for redundant slashes, e.g.
    #   ls /etc//hosts  # works fine
fi
if [ -z "${CAMCOPS_DOCKER_CONFIG_FILENAME}" ]; then
    # Set to default (as per .env file):
    DEFAULT_CONFIG_FILE=camcops.conf
    echo "CAMCOPS_DOCKER_CONFIG_FILENAME not set; using default of ${DEFAULT_CONFIG_FILE}"
    CAMCOPS_DOCKER_CONFIG_FILENAME="camcops.conf"
fi

CFG_ON_HOST="${CAMCOPS_DOCKER_CONFIG_HOST_DIR}/${CAMCOPS_DOCKER_CONFIG_FILENAME}"
CFG_ON_DOCKER="/camcops/cfg/${CAMCOPS_DOCKER_CONFIG_FILENAME}"

echo "Upgrading CamCOPS database to current version."
echo "- Config file on host: ${CFG_ON_HOST}"
echo "- Config file as seen by Docker: ${CFG_ON_DOCKER}"

"${CAMCOPS_SERVER}" upgrade_db --config "${CFG_ON_DOCKER}"
