#!/bin/bash

#==============================================================================
# Absolute path to this script, e.g. /Users/rudolf/mobileweb_camcops/SHIP_DOCS.sh
#==============================================================================

LOCALBASEDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

#==============================================================================
# Install
#==============================================================================

CAMCOPS_VERSION=`perl -ne 'print $1 if /<version>([\d\.]*)<\/version>/;' $LOCALBASEDIR/tiapp.xml`
APK=$LOCALBASEDIR/dist/camcops_${CAMCOPS_VERSION}.apk

ADB=/Users/rudolf/adb

APPID=org.camcops.camcops

DEVICES=`$ADB devices | tail +2 | head -1`  # tail removes the first line
DEVICECOUNT=`echo "$DEVICES" | wc -l`
if [ "$DEVICECOUNT" -eq "0" ]; then
    echo "No device attached"
    exit 1
fi
if [ "$DEVICECOUNT" -ne "1" ]; then
    echo "More than one device attached"
    exit 1
fi
echo "Device: $DEVICES"
#echo "Removing old app (keeping data/cache directories): $APPID"
#$ADB uninstall -k $APPID
echo "Installing/reinstalling: $APK"
$ADB -d install -r "$APK"
