#!/bin/sh

#==============================================================================
# Absolute path to this script, e.g. /Users/rudolf/mobileweb_camcops/SHIP_DOCS.sh
#==============================================================================

LOCALBASEDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

#==============================================================================
# Ship
#==============================================================================

LOCALMOBILEWEBDIR=$LOCALBASEDIR/build/mobileweb

REMOTEUSER="rudolf"
REMOTEHOST="egret"
CONN=$REMOTEUSER@$REMOTEHOST
REMOTEDIR="/srv/www/camcops_mobileweb"

ssh $CONN "rm -rf $REMOTEDIR/*"
scp -r $LOCALMOBILEWEBDIR/* $CONN:$REMOTEDIR/
ssh $CONN "ls $REMOTEDIR/"
