/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package org.camcops.androidtibugfix;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;


@Kroll.module(name="Androidtibugfix", id="org.camcops.androidtibugfix")
public class AndroidtibugfixModule extends KrollModule
{
	public AndroidtibugfixModule()
	{
		super();
	}
}
