#!/bin/bash

#==============================================================================
# Absolute path to this script, e.g. /Users/rudolf/mobileweb_camcops/SHIP_DOCS.sh
#==============================================================================

LOCALBASEDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

#==============================================================================
# Ship
#==============================================================================

$LOCALBASEDIR/SHIP_DOCS_STRINGS
$LOCALBASEDIR/SHIP_ANDROID
