#!/usr/bin/env python
# camcops_server/alembic/versions/0005.py

"""
reduced indexed VARCHAR fields from 255 to 191 for MySQL

Revision ID: 0005
Revises: 0004
Creation date: 2018-09-24 16:25:45.525788

DATABASE REVISION SCRIPT

===============================================================================

    Copyright (C) 2012-2018 Rudolf Cardinal (rudolf@pobox.com).

    This file is part of CamCOPS.

    CamCOPS is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    CamCOPS is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with CamCOPS. If not, see <http://www.gnu.org/licenses/>.

===============================================================================
"""

# =============================================================================
# Imports
# =============================================================================

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# =============================================================================
# Revision identifiers, used by Alembic.
# =============================================================================

revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


# =============================================================================
# The upgrade/downgrade steps
# =============================================================================

# noinspection PyPep8
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_security_account_lockouts', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=191),
               existing_nullable=False)

    with op.batch_alter_table('_security_devices', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=191),
               existing_nullable=True)

    with op.batch_alter_table('_security_groups', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.Unicode(length=191),
               existing_nullable=False)

    with op.batch_alter_table('_security_login_failures', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=191),
               existing_nullable=False)

    with op.batch_alter_table('_security_users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=191),
               existing_nullable=False)

    # ### end Alembic commands ###


# noinspection PyPep8
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('_security_users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=191),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)

    with op.batch_alter_table('_security_login_failures', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=191),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)

    with op.batch_alter_table('_security_groups', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.Unicode(length=191),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)

    with op.batch_alter_table('_security_devices', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=191),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)

    with op.batch_alter_table('_security_account_lockouts', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=191),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
