#!/usr/bin/env python

"""
camcops_server/alembic/versions/0044.py

===============================================================================

    Copyright (C) 2012-2019 Rudolf Cardinal (rudolf@pobox.com).

    This file is part of CamCOPS.

    CamCOPS is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    CamCOPS is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with CamCOPS. If not, see <http://www.gnu.org/licenses/>.

===============================================================================

DATABASE REVISION SCRIPT

taskschedule

Revision ID: 0044
Revises: 0043
Creation date: 2020-01-09 16:26:50.379595

"""

# =============================================================================
# Imports
# =============================================================================

from alembic import op
import sqlalchemy as sa
import cardinal_pythonlib.sqlalchemy.list_types
import camcops_server.cc_modules.cc_sqla_coltypes


# =============================================================================
# Revision identifiers, used by Alembic.
# =============================================================================

revision = '0044'
down_revision = '0043'
branch_labels = None
depends_on = None


# =============================================================================
# The upgrade/downgrade steps
# =============================================================================

# noinspection PyPep8,PyTypeChecker
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_task_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Arbitrary primary key'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__task_schedule')),
    mysql_charset='utf8mb4 COLLATE utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('_task_schedule_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Arbitrary primary key'),
    sa.Column('schedule_id', sa.Integer(), nullable=False, comment='FK to _task_schedule.id'),
    sa.Column('task_table_name', sa.String(length=128), nullable=True, comment="Table name of the task's base table"),
    sa.Column('due_from', camcops_server.cc_modules.cc_sqla_coltypes.PendulumDurationAsIsoTextColType(length=29), nullable=True, comment='Relative time from the start date by which the task may be started'),
    sa.Column('due_by', camcops_server.cc_modules.cc_sqla_coltypes.PendulumDurationAsIsoTextColType(length=29), nullable=True, comment='Relative time from the start date by which the task must be completed'),
    sa.ForeignKeyConstraint(['schedule_id'], ['_task_schedule.id'], name=op.f('fk__task_schedule_item_schedule_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__task_schedule_item')),
    mysql_charset='utf8mb4 COLLATE utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('_task_schedule_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix__task_schedule_item_task_table_name'), ['task_table_name'], unique=False)

    # ### end Alembic commands ###


# noinspection PyPep8,PyTypeChecker
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_task_schedule_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix__task_schedule_item_task_table_name'))

    op.drop_table('_task_schedule_item')
    op.drop_table('_task_schedule')
    # ### end Alembic commands ###
