---
# yamllint disable rule:line-length
name: Build and install Linux packages
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - 'server/setup.py'
            - 'server/camcops_server/**'
            - .github/workflows/build-and-install-packages.yml
            - .github/scripts/build_packages.sh
            - .github/scripts/change_apt_mirror.sh
            - server/tools/MAKE_LINUX_PACKAGES.py
            - server/requirements-deb.txt
            - server/requirements-rpm.txt
jobs:
    build-and-install-package:
        strategy:
            matrix:
                python-version: [3.9, "3.10", 3.11]
                # LTS versions
                os: [ubuntu-22.04, ubuntu-24.04]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Change apt mirror
              run: |
                  set -eux -o pipefail
                  ${GITHUB_WORKSPACE}/.github/scripts/change_apt_mirror.sh
            - name: Build and install debian package
              run: |
                  set -eux -o pipefail
                  ${GITHUB_WORKSPACE}/.github/scripts/build_packages.sh
                  echo installing debian package
                  # Possible scope for confusion here: at this point we should
                  # be running whatever version of Python the package depends
                  # on.
                  server/tools/REINSTALL_DEBIAN_PACKAGE.sh
                  echo checking packages for conflicts
                  /usr/share/camcops/venv/bin/pip check
