---
# yamllint disable rule:line-length
name: Installer
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - 'pyproject.toml'
            - 'server/camcops_server/**'
            - .github/workflows/installer.yml
            - .github/scripts/installer_setup.sh
            - .github/scripts/mysql_docker_setup.sh
            - .github/scripts/post_installation_checks.sh
            - .github/scripts/set_camcops_docker_environment
            - .github/scripts/set_camcops_docker_mysql_environment
            - 'server/docker/**'
            - 'server/installer/**'
jobs:
    installer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - name: Common setup
              run: |
                set -eux -o pipefail
                ${GITHUB_WORKSPACE}/.github/scripts/installer_setup.sh

            - name: Run installer with internal MySQL database
              run: |
                set -eux -o pipefail
                cd ${GITHUB_WORKSPACE}/server/installer
                source ${GITHUB_WORKSPACE}/.github/scripts/set_camcops_docker_environment
                python3 installer_boot.py --camcops_root_dir /camcops --run_locally
                export CAMCOPS_HOME=${GITHUB_WORKSPACE}
                ${GITHUB_WORKSPACE}/.github/scripts/post_installation_checks.sh
                python3 installer_boot.py --camcops_root_dir /camcops --run_locally stop
                rm ${CAMCOPS_DOCKER_CONFIG_HOST_DIR}/${CAMCOPS_DOCKER_CAMCOPS_CONFIG_FILENAME}

            - name: Run installer with external MySQL database
              run: |
                set -eux -o pipefail
                source ${GITHUB_WORKSPACE}/.github/scripts/set_camcops_docker_environment
                source ${GITHUB_WORKSPACE}/.github/scripts/set_camcops_docker_mysql_environment
                ${GITHUB_WORKSPACE}/.github/scripts/mysql_docker_setup.sh
                cd ${GITHUB_WORKSPACE}/server/installer
                python3 installer_boot.py --camcops_root_dir /camcops --run_locally
                export CAMCOPS_HOME=${GITHUB_WORKSPACE}
                ${GITHUB_WORKSPACE}/.github/scripts/post_installation_checks.sh
                python3 installer_boot.py --camcops_root_dir /camcops --run_locally stop
                rm ${CAMCOPS_DOCKER_CONFIG_HOST_DIR}/${CAMCOPS_DOCKER_CAMCOPS_CONFIG_FILENAME}
            - name: Dump logs
              if: failure()
              run: |
                  set -euo pipefail
                  cd ${GITHUB_WORKSPACE}
                  sleep 120

                  compose_file1=${GITHUB_WORKSPACE}/server/docker/dockerfiles/docker-compose.yaml
                  compose_file2=${GITHUB_WORKSPACE}/server/docker/dockerfiles/docker-compose-mysql.yaml

                  if [ -f "${compose_file1}" ]; then
                      compose_args=(-f "${compose_file1}")

                      if [ -f "${compose_file2}" ]; then
                          compose_args+=(-f "${compose_file2}")
                          docker compose "${compose_args[*]}" logs mysql
                      fi
                      echo "Dumping Docker logs"
                      docker compose "${compose_args[*]}" logs rabbitmq
                      docker compose "${compose_args[*]}" logs camcops_workers
                      docker compose "${compose_args[*]}" logs camcops_scheduler
                      docker compose "${compose_args[*]}" logs camcops_server
                      docker compose "${compose_args[*]}" logs flower
                  fi
