---
# yamllint disable rule:line-length
name: Installer
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - 'pyproject.toml'
            - 'server/camcops_server/**'
            - .github/workflows/installer.yml
            - .github/scripts/installer_setup.sh
            - .github/scripts/mysql_docker_setup.sh
            - .github/scripts/post_installation_checks.sh
            - .github/scripts/set_camcops_docker_environment
            - .github/scripts/set_camcops_docker_mysql_environment
            - 'server/docker/**'
            - 'server/installer/**'
jobs:
    installer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - name: Run installer with interal MySQL database
              run: |
                set -eux -o pipefail
                source ${GITHUB_WORKSPACE}/.github/scripts/set_camcops_docker_environment
                ${GITHUB_WORKSPACE}/.github/scripts/installer_setup.sh
                cd ${GITHUB_WORKSPACE}/server/installer
                python3 installer_boot.py --camcops_root_dir /camcops --run_locally
                export CAMCOPS_HOME=${GITHUB_WORKSPACE}
                ${GITHUB_WORKSPACE}/.github/scripts/post_installation_checks.sh
                python3 installer_boot.py --camcops_root_dir /camcops --run_locally stop
                rm ${CAMCOPS_DOCKER_CONFIG_HOST_DIR}/${CAMCOPS_DOCKER_CAMCOPS_CONFIG_FILENAME}

            - name: Run installer with external MySQL database
              run: |
                set -eux -o pipefail
                source ${GITHUB_WORKSPACE}/.github/scripts/set_camcops_docker_mysql_environment
                ${GITHUB_WORKSPACE}/.github/scripts/installer_setup.sh
                ${GITHUB_WORKSPACE}/.github/scripts/mysql_docker_setup.sh
                cd ${GITHUB_WORKSPACE}/server/installer
                python3 installer_boot.py --camcops_root_dir /camcops --run_locally
                export CAMCOPS_HOME=${GITHUB_WORKSPACE}
                ${GITHUB_WORKSPACE}/.github/scripts/post_installation_checks.sh
                python3 installer_boot.py --camcops_root_dir /camcops --run_locally stop
                rm ${CAMCOPS_DOCKER_CONFIG_HOST_DIR}/${CAMCOPS_DOCKER_CAMCOPS_CONFIG_FILENAME}
