name: Temporary test of Qt git clone

on:
    push:
        paths:
            - .github/workflows/temp.yml

jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout Qt
              run: |
                set -euxo pipefail
                QT6_DIR=${HOME}/qt_local_build/src/qt6
                mkdir -p ${QT6_DIR}
                git clone git://code.qt.io/qt/qt5.git ${QT6_DIR}
                cd ${QT6_DIR}
                git tag
                git checkout v6.5.5-lts-lgpl
