---
name: Temp

on:
    push:
        paths:
          - .github/workflows/temp.yml

jobs:
    temp:
        runs-on: ubuntu-22.04
        steps:
            - name: Write file
              run: |
                  set -euo pipefail
                  echo "Testing..." > /tmp/test.txt
            - name: Work out commit
              # TODO: This seems to be ignored and instead the release gets
              # called uncommitged-<some hash>
              id: vars
              run: |
                  set -euo pipefail
                  echo "commit=qt_${GITHUB_SHA}" >> $GITHUB_OUTPUT
            - name: Release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: "/tmp/test.txt"
                  token: ${{ secrets.GITHUB_TOKEN }}
                  prerelease: true
                  draft: true
                  body: Testing draft release (${{ steps.vars.outputs.commit }})
                  name: Test, please ignore (${{ steps.vars.outputs.commit }})
                  commit: ${{ steps.vars.outputs.commit }}
