---
name: Temp

on:
    push:
        paths:
          - .github/workflows/temp.yml

jobs:
    temp:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - name: Write file
              run: |
                  set -euo pipefail
                  echo "Testing..." > /tmp/test.txt
            - name: Work out tag
              id: vars
              run: |
                  set -euo pipefail
                  QT_VERSION="$(sed 's/[a-z-]//g' ${GITHUB_WORKSPACE}/tablet_qt/qt_version.txt)"
                  echo "tag=qt_${QT_VERSION}_${GITHUB_SHA}" >> $GITHUB_OUTPUT
            - name: Create tag
              run: |
                  set -euo pipefail
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git tag ${{ steps.vars.outputs.tag }}
                  git push origin "${{ steps.vars.outputs.tag }}"
            - name: Release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: "/tmp/test.txt"
                  token: ${{ secrets.GITHUB_TOKEN }}
                  prerelease: true
                  draft: true
                  body: Testing draft release (${{ steps.vars.outputs.tag }})
                  name: Test, please ignore (${{ steps.vars.outputs.tag }})
                  tag: ${{ steps.vars.outputs.tag }}
